LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

#LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_MODULE_RELATIVE_PATH := hw

LOCAL_C_INCLUDES += $(LOCAL_PATH)/../common
LOCAL_C_INCLUDES += $(TARGET_HARDWARE_INCLUDE)

LOCAL_SHARED_LIBRARIES := liblog libEGL libsync libion libutils libcutils
LOCAL_SRC_FILES := hwtimewarp.cpp hwtw_sunxi_ion.cpp
LOCAL_MODULE := hwtimewarp.default
LOCAL_MODULE_TAGS := optional

LOCAL_CPPFLAGS := -std=c++11

LOCAL_CFLAGS:= -D_LOG_TAG_=\"AtwHal\" -DTARGET_BOARD_PLATFORM=$(TARGET_BOARD_PLATFORM)

LOCAL_CPPFLAGS += -DDEBUG_NORMAL_LAYER=0

LOCAL_CPPFLAGS += -DDEBUG_RUN_ON_H8=0

include $(BUILD_SHARED_LIBRARY)
